// <auto-generated />
namespace AngularCRUD_aspMvc5asBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class sandy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sandy));
        
        string IMigrationMetadata.Id
        {
            get { return "201411140450477_sandy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
